### ISSUE TITLE
AdiIRC Enahncement

### ISSUE THREAD

**Issue by WildClaudio** [solbu/Peace-and-Protection#25]
Hello is there a way to be able to run PnP latest version using AdiIRC IRC Client it runs all mIRC snippets/scripts/remotes so basically is a mIRC version but with a 2016 GUI and alot of options ... i`v tried to  load it but seams that PnP is checking for the version as AdiIRC is only at version 2.4 but its constantly updated and its a 2016 IRC Client PnP will give errors on load  that version is not matching  here are the examples

for both releases latest and 4.22

[01:08:43] \* Loaded script 'C:\Program Files\AdiIRC\script\first.mrc'
[01:10:12] \* /hmake: table 'pnp.startup' exists (line 40, first.mrc)
[01:10:12] \* Loaded script 'C:\Program Files\AdiIRC\script\first.mrc'

[01:08:43] Peace and Protection requires mIRC 7.43 or later to run! (you are using 2.4)
[01:08:43] Peace and Protection requires mIRC 7.43 or later to run! (you are using 2.4)

i`v loaded partial scripts from PnP and they are working / as i am a PnP script runner since almost 8/9 years i would love to be able to load/use it with AdiIRC ...as mIRC  is using the same GUI since i know it and its a PAY irc client AdiIRC its a free and open source irc client that  is much better then mIRC in my opinion !!! thank you in advance 

here you can find what adiirc has/or not regarded with mIRC regarding script commands !!!
https://dev.adiirc.com/projects/adiirc/wiki/Scripting_Commands

thank you in advance !!!

**Comment by solbu** [comment]
First, AdiIRC is not Free and Open Source Software, it is just as proprietary as mIRC. I just doesn't cost money. Just because something is Free of charge, doesn't make it Free Software. :-)

Second, we can't fix this issue as we don't have the manpower. And also because that is extending the script, which is not wat we do. We are committed to making it work on mIRC. If if works on something other than mIRC fine, but we will not contribute to making it happen.
