### ISSUE TITLE
MOTD skewed on for example irc.efnet.nl (windmill)

### ISSUE THREAD

**Issue by ghost** [solbu/Peace-and-Protection#53]
**Describe the bug**
When MOTD is displayed in separate @MOTD window it doesn't seem to honor spaces in ascii art.

**To Reproduce**
1. PnP Options > Display > Other > Display MOTD to \@MOTD window = checked;
2. Connect: `//var %nick $+(test,$base($rand(0,9999),10,10,4)), %altnick $+(%nick,_) | server irc.efnet.nl -i %nick %altnick`
2. Observe MOTD window (see screenshot);

**Expected behavior**
Dutch windmill to show correctly...

**Screenshots**
<img width="583" alt="image" src="https://user-images.githubusercontent.com/13683523/153586887-e8295f53-0c3b-4bf8-87ae-17275c42ad3b.png">

**Please complete the following information:**
 - mIRC version: 7.67
 - PnP version: 4.22.9

**Additional context**
See for example this mirc forum post: https://forums.mirc.com/ubbthreads.php/topics/263560

**Comment by solbu** [comment]
This might be due to the font being used in mIRC.
The ascii arts on IRC is dependent on the user using a fixed width font, where the width of the characters uses the same screen space regardless.
An example is «m» and «i». They are not the same width, but a fixed width font makes them use the same space.

**Comment by ghost** [comment]
> This might be due to the font being used in mIRC.
> The ascii arts on IRC is dependent on the user using a fixed width font, where the width of the characters uses the same screen space regardless.
> An example is «m» and «i». They are not the same width, but a fixed width font makes them use the same space.

I've just tested a brand new install with mIRC 7.67 and PnP 4.22.9 using the Consolas fixed width font and it still bugs. Work in progress :)

**Comment by RealKindOne** [comment]
mIRC "eats" spaces.

http://www.xise.nl/mirc/wiki/doku.php?id=spaces

**Comment by solbu** [comment]
> mIRC "eats" spaces.
> 
> http://www.xise.nl/mirc/wiki/doku.php?id=spaces

This has nothing to do with spaces, it is about how much pixel space a character uses, there is a difference.
The letter «M» use more pixels on a screen than the letter «I», a fixed width font makes them use the same amount of pixels.
MOTD ascii arts depends on the client using a fixed width font for it to render properly.

I don't know if PnP changes the default font when one install pnp. I really do think is has to do with what font is used in your mIRC client.
I know that because I see the same «problem» in my HexChat client on GNU/Linux, but I have deliberately changed the font I use to one that looks the same as what I used when I still used mIRC and PnP (wich I used from about 2001 untill 2008, when I switched to GNU/Linux).

**Comment by solbu** [comment]
Also, the spaces being removed is a deliberate change that mIRC changed some years back, and we can't fix it in any way. It is hardcoded into mIRC to remove aditional spacec in text.

Example:
```
«This    is    spaces» will be forefully changed by mIRC to «This is spaces»
```
... and there is no toggle switch or button you can click to disable it.

**Comment by solbu** [comment]
At least it used to be back when I still used mIRC. :-)

**Comment by solbu** [comment]
And I think I found out what does this.
This is listed by Pai in the pp-faq.txt file.

> Q; Why do you remove doubled spaces in text that I see or type?
> A; Because of how mIRC works, any script that changes display
>    will, as a side-effect, remove doubled spaces. There is no
>    way around this if you use a custom text scheme.
> 
>    You may use "/text off" to disable PnP's text theme features,
>    and then doubled spaces will act as normal in most cases.
> 
>    You can also press Alt+Q to enable mIRC's second channel editbox,
>    and type or paste your text there. PnP ignores anything typed
>    into this box, allowing spacing to be retained.
> 
>    There is no way for PnP to handle sound filenames with doubled
>    spaces. This is simply a limitation of mIRC.

**Comment by ghost** [comment]
https://github.com/peace-and-protection/Peace-and-Protection/blob/1746c74d8133c1b2574032c498617c702dd1a4bd/script/rawdisp.mrc#L605-L607

I've had success by changing the above code to the below code:

```
  var %text $regsubex($rawmsg,/(\s)/g,$chr(160))
  var %text2 $mid(%text,$calc(1 + $pos(%text,:,2)))
  tokenize 160 %text2
  if ((($1 == -) && ($2 == $null)) || ($1 == $null)) set -u %::text  
  elseif ($1 == -) set -u %::text     $right(%text2,-1)
  else set -u %::text     %text2
```

P.S.: You need to select and save a monospace font such as 'Consolas' in PnP's theme editor.

![image](https://user-images.githubusercontent.com/13683523/169654850-89b21de9-0cfb-435a-a1af-9fc80c1b7ca8.png)

![image](https://user-images.githubusercontent.com/13683523/169654956-9abd880d-52ba-4076-a452-1d7e5742bcd7.png)

**Comment by ghost** [comment]
If you're wondering like me why you can't reproduce this, it's because I had forgotten to mention that you have to apply PnP
s /fontfixer to the PnP windows! (It's in PnP > Options > Fontfixer...)
